import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';
import sharp from 'sharp';
import crypto from 'node:crypto';
import {attachOriginalAlpha} from './image-mask.mjs';

const script = path.resolve('scripts/build-images.mjs');
test('publication gate converts source formats, preserves originals and rejects unreviewed or invalid output', async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'romic-image-test-'));
  try {
    await fs.mkdir(path.join(root, 'site/assets/products'), { recursive: true });
    await fs.writeFile(path.join(root, 'site/data.js'), "const ROMIC_PRODUCTS=[{id:'bag',name:'bag',he:'Bag description',en:'Bag description',image:'test.png',gallery:['test.png','model.png']}];");
    await fs.writeFile(path.join(root, 'site/index.html'), '<link href="styles.css?v=old"><script src="app.js?v=old"></script>');
    await fs.mkdir(path.join(root, 'site/he'), { recursive: true });
    await fs.mkdir(path.join(root, 'site/en'), { recursive: true });
    const productTemplate = '<!doctype html><html><head><title>Bag — Romic</title><meta name="description" content="Bag details."><meta property="og:type" content="website"><meta property="og:site_name" content="ROMIC"><meta property="og:title" content="Handmade bag | ROMIC"><meta property="og:description" content="Bag details."><meta property="og:url" content="https://romic.co.il/he/product.html"><meta property="og:image" content="https://romic.co.il/assets/products/test.webp"><meta property="og:image:alt" content="Bag by ROMIC"></head><body data-page="product"></body></html>';
    await fs.writeFile(path.join(root, 'site/he/product.html'), productTemplate);
    await fs.writeFile(path.join(root, 'site/en/product.html'), productTemplate.replace('/he/product.html','/en/product.html'));
    await fs.writeFile(path.join(root, 'site/styles.css'), 'body{color:black}');
    await fs.writeFile(path.join(root, 'site/app.js'), '// first version');
    await fs.writeFile(path.join(root, 'image-policy.json'), JSON.stringify({ margin:.08, customModels:[], colorBackgrounds:{}, productBackgrounds:{bag:'#eee'}, derivatives:{'cards/600':600,'gallery-thumbs':240,'conveyor/480':480} }));
    const source = path.join(root, 'site/assets/products/test.png');
    await sharp({create:{width:100,height:100,channels:3,background:'#336699'}}).png().toFile(source);
    const scenePath = path.join(root,'site/assets/products/model.png');
    await sharp({create:{width:100,height:180,channels:3,background:'#336699'}}).png().toFile(scenePath);
    const originalScene = await fs.readFile(scenePath);
    const original = await fs.readFile(source);
    await fs.mkdir(path.join(root,'image-masks'),{recursive:true});
    const maskPath = path.join(root,'image-masks/test.png');
    const white = await sharp({create:{width:50,height:50,channels:3,background:'#fff'}}).png().toBuffer();
    await sharp({create:{width:100,height:100,channels:3,background:'#000'}}).composite([{input:white,left:25,top:25}]).greyscale().png().toFile(maskPath);
    const attached = await sharp(await attachOriginalAlpha(original,await fs.readFile(maskPath))).raw().toBuffer({resolveWithObject:true});
    const decoded = await sharp(original).raw().toBuffer();
    assert.equal(attached.info.channels,4);
    for(let i=0;i<10000;i++)assert.deepEqual(attached.data.subarray(i*4,i*4+3),decoded.subarray(i*3,i*3+3));
    assert.equal(attached.data[3],0);
    assert.equal(attached.data[(50*100+50)*4+3],255);
    await fs.writeFile(path.join(root,'image-masks.json'),JSON.stringify({'assets/products/test.png':{mask:'image-masks/test.png',sourceSha256:crypto.createHash('sha256').update(original).digest('hex'),bbox:[0,0,100,100]}}));
    const run = (...args) => spawnSync(process.execPath, [script,...args], {cwd:root,encoding:'utf8'});
    assert.match(run().stderr, /Visual review required/);
    assert.equal(run('--review').status, 0);
    const firstBuild = run();
    assert.equal(firstBuild.status, 0, firstBuild.stderr);
    const sharePage = await fs.readFile(path.join(root, '_site/he/product-bag.html'), 'utf8');
    assert.match(sharePage, /property="og:title" content="bag \| ROMIC"/);
    assert.match(sharePage, /property="og:image" content="https:\/\/romic\.co\.il\/assets\/products\/model\.webp\?v=romic-/);
    assert.match(sharePage, /property="og:url" content="https:\/\/romic\.co\.il\/he\/product-bag\.html"/);
    assert.match(await fs.readFile(path.join(root, '_site/sitemap.xml'), 'utf8'), /https:\/\/romic\.co\.il\/he\/product-bag\.html/);
    assert.equal(run('--check').status, 0);
    const versionBefore = await fs.readFile(path.join(root, '_site/index.html'), 'utf8');
    await fs.appendFile(path.join(root, 'site/styles.css'), '\nbutton{min-height:44px}');
    assert.equal(run().status, 0);
    const versionAfterCss = await fs.readFile(path.join(root, '_site/index.html'), 'utf8');
    assert.notEqual(versionBefore, versionAfterCss, 'CSS changes must invalidate the browser cache');
    await fs.appendFile(path.join(root, 'site/app.js'), '\n// updated checkout');
    assert.equal(run().status, 0);
    assert.notEqual(versionAfterCss, await fs.readFile(path.join(root, '_site/index.html'), 'utf8'), 'App changes must invalidate the browser cache');
    const published = path.join(root, '_site/assets/products/test.webp');
    const meta = await sharp(published).metadata();
    assert.deepEqual([meta.format,meta.width,meta.height], ['webp',1200,1500]);
    const backdrop=await sharp(published).extract({left:150,top:300,width:1,height:1}).raw().toBuffer();
    for(const value of backdrop)assert.ok(Math.abs(value-238)<=3,'masked backdrop must replace original photograph');
    assert.deepEqual(await fs.readFile(source),original);
    const scene = await sharp(path.join(root,'_site/assets/products/model.webp')).metadata();
    assert.deepEqual([scene.width,scene.height],[100,180], 'Full-scene galleries retain native proportions without upscaling');
    assert.deepEqual(await fs.readFile(scenePath),originalScene);
    const corner = await sharp(path.join(root,'_site/assets/products/model.webp')).extract({left:0,top:0,width:1,height:1}).raw().toBuffer();
    assert.ok(Math.abs(corner[0]-51)<5 && Math.abs(corner[1]-102)<5 && Math.abs(corner[2]-153)<5, 'No pale frame is added to the scene');
    const conveyor = await sharp(path.join(root, '_site/assets/conveyor/480/bag.webp')).metadata();
    assert.deepEqual([conveyor.width,conveyor.height],[480,600]);
    assert.match(await fs.readFile(path.join(root,'_site/data.js'),'utf8'), /test.webp/);
    await sharp({create:{width:100,height:100,channels:3,background:'#fff'}}).webp().toFile(published);
    assert.match(run('--check').stderr, /Nonstandard image/);
    await fs.appendFile(maskPath,Buffer.from([0]));
    assert.match(run().stderr,/Visual review required for mask/);
    assert.equal(run('--review').status,0);
    await fs.appendFile(source, Buffer.from([0]));
    assert.match(run().stderr, /Visual review required/);
    assert.match(run('--review').stderr,/Prepare a current background mask/);
    await fs.rm(source);
    assert.match(run().stderr, /Missing image/);
  } finally { await fs.rm(root,{recursive:true,force:true}); }
});
